name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # Restore dependencies for Module project
    - name: Restore dependencies for Module
      run: dotnet restore src/Module/Module.csproj

    # Build Module project
    - name: Build Module
      run: dotnet build src/Module/Module.csproj --no-restore

    # Test using the Tests project
    - name: Test
      run: dotnet test src/Tests/Tests.csproj --no-build --verbosity normal
